//! Emits the cache-resolved chrome-headless-shell path.
//!
//! The binary itself is NOT downloaded at build time anymore: acquisition
//! moved to runtime (`src/chromium_ensure.rs`), which prefers an already
//! cached bundle or a system Chrome/Chromium/Edge and only downloads on
//! first actual use (view/export).

use std::env;
use std::path::PathBuf;

#[path = "src/cache.rs"]
mod cache;

fn platform_slug() -> Option<&'static str> {
    let os = env::var("CARGO_CFG_TARGET_OS").ok()?;
    let arch = env::var("CARGO_CFG_TARGET_ARCH").ok()?;
    match (os.as_str(), arch.as_str()) {
        ("macos", "x86_64") => Some("mac-x64"),
        ("macos", "aarch64") => Some("mac-arm64"),
        ("linux", "x86_64") => Some("linux64"),
        ("windows", "x86_64") => Some("win64"),
        _ => None,
    }
}

fn binary_filename() -> &'static str {
    if cfg!(target_os = "windows") {
        "chrome-headless-shell.exe"
    } else {
        "chrome-headless-shell"
    }
}

fn main() {
    // Re-run when any path-affecting env var changes.
    println!("cargo:rerun-if-env-changed=DRAWIO_AGENT_CACHE_DIR");
    println!("cargo:rerun-if-env-changed=XDG_CACHE_HOME");
    println!("cargo:rerun-if-env-changed=HOME");
    println!("cargo:rerun-if-env-changed=LOCALAPPDATA");

    let out_dir = env::var("OUT_DIR").expect("OUT_DIR");
    let emitted = PathBuf::from(out_dir).join("bundled_chromium.rs");

    // 路径照缓存布局发射（运行时按需下载填充；不存在 = 还没拉取过）。
    let path_str = platform_slug().map(|platform| {
        // 与 src/chromium_ensure.rs::PINNED_CHROMIUM_VERSION 保持同步
        cache::cache_root()
            .join("chrome-headless-shell")
            .join("131.0.6778.85")
            .join(platform)
            .join(format!("chrome-headless-shell-{platform}"))
            .join(binary_filename())
            .to_string_lossy()
            .into_owned()
    });

    let content = format!(
        "/// Auto-generated by build.rs. Do not edit.
\
         /// Cache-resolved chrome-headless-shell path (downloaded lazily at\
         /// runtime by chromium_ensure).
\
         pub const BUNDLED_CHROMIUM_PATH: Option<&'static str> = {path_str:?};
"
    );
    std::fs::write(&emitted, content).expect("write bundled_chromium.rs");
}
